name: 'Karnot Cloud Pro Action'
description: 'Deploy to karnot cloud using a YAML configuration'
inputs:
  input_file:
    description: 'Path to the YAML configuration file'
    required: true
  environment:
    description: 'The environment to deploy to'
    required: true
  KARNOT_CLOUD_URL:
    description: 'The base URL of your Karnot Cloud instance'
    required: true
  KARNOT_CLOUD_TOKEN:
    description: 'Your Karnot Cloud API token'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        cd ${{ github.action_path }}
        node index.js
      shell: bash
