name: 'Karnot Cloud Pro'
description: 'Deployment CI for Karnot Cloud'
inputs:
  input_file:
    description: 'Path to the deployment file'
    required: true
  environment:
    description: 'Environment to deploy'
    required: true
  KARNOT_CLOUD_URL:
    description: 'Karnot Cloud URL'
    required: true
  KARNOT_CLOUD_TOKEN:
    description: 'Karnot Cloud Token'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        node ${{ github.action_path }}/index.js
      shell: bash
      env:
        INPUT_FILE: ${{ inputs.input_file }}
        ENVIRONMENT: ${{ inputs.environment }}
        KARNOT_CLOUD_URL: ${{ inputs.KARNOT_CLOUD_URL }}
        KARNOT_CLOUD_TOKEN: ${{ inputs.KARNOT_CLOUD_TOKEN }}